name: 'Terraform Plan'
on:
    workflow_dispatch:

env:
    TF_CLOUD_ORGANIZATION: 'Azure-Linux-VM' # Replace with your Terraform Cloud organization name
    TF_WORKSPACE: 'PlanDryRun' # Replace with your Terraform Cloud workspace name
    TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }} # Set this secret in your GitHub repository settings
    CONFIG_DIRECTORY: './' # Directory containing your Terraform configuration files

jobs:
    terraform-plan:
        if: github.repository == 'shivakpkp/terraform-azure-linux-vm'
        name: 'Terraform Plan'
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Upload Configuration
          uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.2
          id: plan-upload
          with:
            organization: ${{ env.TF_CLOUD_ORGANIZATION }}
            token: ${{ env.TF_API_TOKEN }}
            workspace: ${{ env.TF_WORKSPACE }}
            directory: ${{ env.CONFIG_DIRECTORY }}
            speculative: true

        # - name: Create Plan Run
        #   uses: hasicorp/tfc-workflows-github/actions/create-run@v1.0.0
        #   id: plan-run
        #   with:
        #     workspace: ${{ env.TF_WORKSPACE }}
        #     configuration_version: ${{ steps.plan-upload.outputs.configuration_version_id }}
        #     plan_only: true
        
        # - name: Get Plan Output
        #   uses: hasicorp/tfc-workflows-github/actions/plan-output@v1.0.0
        #   id: plan-output
        #   with:
        #     plan: ${{ fromJson(steps.plan-run.outputs.payload).data.relationships.plan.data.id }}
